[project]
name = "on-chain-identity-registry"
clarity_version = "2.1.0"
description = "A basic on-chain identity registry using Clarity"
authors = ["Midorichie <hamsohood@gmail.com>"]

[contracts.identity-registry]
path = "contracts/identity-registry.clar"
